### ISSUE TITLE
Request : Auto add personnal spell effects

### ISSUE THREAD

**Issue by uniwars** [reyzor1991/foundry-vtt-pf2e-action-support#4]
Hi, since it seems there is some duplication of effects (with rage for example) with Pf2e Animation which also has a feature to add effect when action/spell is used and MrVauxs is considering dropping this feature, would that be possible to cover personnal range spells (spells with nothing in "range") for them to auto add their effects to the caster when they are casted ?
For example shield, false life, vital beacon. I don't know if that stays in the scope of the module, casting a spell is still an action I guess.

**Comment by reyzor1991** [comment]
I know about issue with Pf2e Animation duplication, looks like Pf2e Animation not see already applied effect.
I planned to add as many as possible spells/actions to the module. Likewise, I will start from spells with already created effects, for example shield, vital beacon, but for spells like false life I will add later because for them, I need to create effect.

**Comment by uniwars** [comment]
Thanks for the answer, yeah I didn't thought that false life doesn't have an effect yet, there should be a reason why system didn't had one

**Comment by reyzor1991** [comment]
I think, because there are a lot of spells and need time to create effects for each of them. If you have spells that you often use or want to see in next release, post here, and I will add in next release. Shield, Vital Beacon—will be there

**Comment by reyzor1991** [comment]
Shield, Vital Beacon—added in 0.0.19
 Next part of spells will be soon
